@startuml
left to right direction
skinparam packageStyle rectangle

actor "Клиент" as Client
actor "Менеджер" as Manager
actor "Администратор" as Admin


Client --> (Регистрация)
Client --> (Просмотр каталога тура)
Client --> (Выбор тура)
Client --> (Бронирование тура)
Client --> (Оплата тура)
Client --> (Просмотр своих броней)

(Регистрация) ..> (Вход в систему) : <<include>>
(Просмотр каталога тура) ..> (Вход в систему) : <<include>>
(Выбор тура) ..> (Вход в систему) : <<include>>
(Бронирование тура) ..> (Вход в систему) : <<include>>
(Оплата тура) ..> (Вход в систему) : <<include>>
(Просмотр своих броней) ..> (Вход в систему) : <<include>>



Manager --> (Подтверждение бронирования)
Manager --> (Оформление продажи)
Manager --> (Просмотр списка броней)

(Подтверждение бронирования) ..> (Вход в систему) : <<include>>
(Оформление продажи) ..> (Вход в систему) : <<include>>
(Просмотр списка броней) ..> (Вход в систему) : <<include>>

Admin --> (Управление турами)
Admin --> (Управление пользователями)

(Управление турами) ..> (Вход в систему) : <<include>>
(Управление пользователями) ..> (Вход в систему) : <<include>>

(Вход в систему) ..> (Авторизация пользователя) : <<include>>
@enduml